teams_subreddit = {
  "hawks": "r/AtlantaHawks",
  "celtics": "r/BostonCeltics",
  "nets": "r/BrooklynNets",
  "hornets": "r/CharlotteHornets",
  "bulls": "r/ChicagoBulls",
  "cavs": "r/ClevelandCavs",
  "mavericks": "r/DallasMavericks",
  "nuggets": "r/DenverNuggets",
  "pistons": "r/DetroitPistons",
  "warriors": "r/warriors",
  "rockets": "r/rockets",
  "pacers": "r/pacers",
  "clippers": "r/LAClippers",
  "lakers": "r/lakers",
  "grizzlies": "r/memphisgrizzlies",
  "heat": "r/heat",
  "bucks": "r/MkeBucks",
  "timberwolves": "r/timberwolves",
  "pelicans": "r/NOLAPelicans",
  "knicks": "r/NYKnicks",
  "thunder": "r/Thunder",
  "magic": "r/OrlandoMagic",
  "sixers": "r/sixers",
  "suns": "r/suns",
  "blazers": "r/ripcity",
  "kings": "r/kings",
  "spurs": "r/NBASpurs",
  "raptors": "r/torontoraptors",
  "jazz": "r/UtahJazz",
  "wizards": "r/washingtonwizards"
}

teams_name = [
    "hawks", 
    "celtics", 
    "nets", 
    "hornets", 
    "bulls", 
    "cavs", 
    "mavericks", 
    "nuggets", 
    "pistons", 
    "warriors", 
    "rockets", 
    "pacers", 
    "clippers", 
    "lakers", 
    "grizzlies", 
    "heat", 
    "bucks", 
    "timberwolves", 
    "pelicans", 
    "knicks", 
    "thunder", 
    "magic", 
    "sixers", 
    "suns", 
    "blazers", 
    "kings", 
    "spurs", 
    "raptors", 
    "jazz", 
    "wizards"
    ]
